### PR TITLE
Fix bottom sheet crash on iOS

### LINKED ISSUE #93: Crash in BottomSheet component in iOS
I am trying to have a bottomsheet, on Android it works fine, but on iOS it crashes at startup. I feel like it's because of the `.roundToPx()` in offset function since it is rounding containerHeight which is not specified.

Here is how I call it.

        val bottomSize = WindowInsets.navigationBars.asPaddingValues().calculateBottomPadding()

        val peek = SheetDetent("peek") { containerHeight, sheetHeight ->
            80.dp + bottomSize
        }

        val center = SheetDetent("center") { containerHeight, sheetHeight ->
            containerHeight * 0.5f
        }

        val sheetState = rememberBottomSheetState(
            initialDetent = FullyExpanded,
            detents = listOf(peek, center, FullyExpanded),
            animationSpec = tween(250, easing = FastOutSlowInEasing)
        )

        val offset = sheetState.offset
        val maxHeightPixels = with(LocalDensity.current) { maxHeight.toPx() }
        val progress = (1 - offset / maxHeightPixels).coerceIn(0f, 0.5f) / 0.5f

        BottomSheet(
            state = sheetState,
            modifier = Modifier.fillMaxWidth()
                .background(
                    Color.White, RoundedCornerShape(
                        topStart = 16.dp * progress,
                        topEnd = 16.dp * progress
                    )
                ),
        ) {

### PR DESCRIPTION
**Pull request by LukasAnda**
Fixes #93

### CODE REVIEW

File: core/src/commonMain/kotlin/BottomSheet.kt [hunk 1]
```diff
@@ -37,6 +38,7 @@ import androidx.compose.ui.unit.*
 import com.composables.core.androidx.compose.foundation.gestures.*
 import com.composeunstyled.LocalContentColor
 import kotlin.jvm.JvmName
+import kotlin.text.toInt
```
Comment (alexstyl) [inline core/src/commonMain/kotlin/BottomSheet.kt:41]: Is this needed?

File: core/src/commonMain/kotlin/BottomSheet.kt [hunk 2]
```diff
@@ -422,6 +424,8 @@ fun BottomSheet(
                             val requireOffset = state.anchoredDraggableState.requireOffset()
                             val y = requireOffset.toInt()
                             IntOffset(x = 0, y = y)
+                        } else if(containerHeight == Dp.Unspecified) {
```
Comment (alexstyl) [inline core/src/commonMain/kotlin/BottomSheet.kt:427]: This doesn't seem to be formatted - i think if is missing a space. Please format the code

**Review by alexstyl — CHANGES_REQUESTED** [review]
A few small issues but overall looks good.

Also, kindly update your commit message to be descriptive:

`Fix bottom sheet crash on iOS` does not explain the changes you did in the code.

A better commit message would be 

`Ensure containerHeight is specified when setting BottomSheet's offset 

Fixes: {URL OF THE ISSUE THAT IT IS BEING FIXED`

File: core/src/commonMain/kotlin/BottomSheet.kt (hunk 1 above)
Comment (LukasAnda) [reply core/src/commonMain/kotlin/BottomSheet.kt:41]: Accidental import, removed!

File: core/src/commonMain/kotlin/BottomSheet.kt (hunk 2 above)
Comment (LukasAnda) [reply core/src/commonMain/kotlin/BottomSheet.kt:427]: Fixed!

File: core/src/commonMain/kotlin/com/composeunstyled/TextField.kt [hunk 3]
```diff
@@ -245,6 +245,7 @@ fun TextField(
     keyboardOptions: KeyboardOptions = KeyboardOptions.Default,
     visualTransformation: VisualTransformation = VisualTransformation.None,
     interactionSource: MutableInteractionSource? = null,
+    textColor: Color = Color.Unspecified,
```
Comment (alexstyl) [inline core/src/commonMain/kotlin/com/composeunstyled/TextField.kt:248]: I think you would need to update your branch with the latest changes. After that, we are good to merge

Comment (LukasAnda) [reply core/src/commonMain/kotlin/com/composeunstyled/TextField.kt]: Synced my fork with your code :) Now it should be up to date

**Comment by alexstyl** [comment]
Merged. Thanks for the contribution Lukas
